[package]
name = "pinger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ping-rs = "0.1.2"
eframe = "0.26.2"
env_logger = "0.11.2"
serde = { version = "1.0.202", features = ["derive"] }
toml = "0.8.13"

